// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayeirdvewlzglcljncpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5ZWlyZHZld2x6Z2xjbGpuY3B5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3ODk1MjYsImV4cCI6MjA1ODM2NTUyNn0.a9LYy3W6EFJxPs34ROHBmnG2vbL6ua-DcF8Djl7k4xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);